### ISSUE TITLE
Create a web based application to interface with our database

### ISSUE THREAD

**Issue by scavet64** [scavet64/GradDatabaseProject#19]
- [x] log in an admin
  - [x] edit our customers (entity table)
  - [x] view all customers
    - [x] List all customers from all databases
    - [x] List all customers from **OUR** databases
    - [x] Edit our customers from **OUR** database
    - [x] Delete a customer from **OUR** database 
  - [x] edit our supplier (entity table)
    - [x] List all suppliers
    - [x] Edit our suppliers information
    - [x] Delete a supplier
  - [x] edit our product (entity table)
  - [x] view all products
  - [x] view product inventory
  - [x] view restocking orders
  - [x] Create a report Controller and views for...
	- [x] view products below min inv
	- [x] view inactive customers
	- [x] view products not selling well
	- [x] highly wished for products in each category
	- [x] wished for products never purchased
- [x] Register as a new user
  - [x] Register as an existing customer from another database
  - [x] Register as new customer
- [x] log in a user
  - [x] view all products
	- [x] Filter by Category
	- [x] see average rating
	- [x] see weighted average rating
  - [x] add product to shopping cart
  - [x] view shopping cart
  - [x] place order from shopping cart
  - [x] view orders
  - [x] see when orders will ship
  - [x] add product to wishlist
  - [x] view wishlist
  - [x] view suggested products
  - [x] rate product

**Comment by jscavetta95** [comment]
>:^O
